### ISSUE TITLE
Importreplace not working as intended

### ISSUE THREAD

**Issue by arsaboo** [edgars-supe/beets-importreplace#1]
Spotify often has `(Original Motion Picture Soundtrack)` in the album title that I was hoping to remove using this plugin. I installed the plugin and have added the following block to the config:

```
plugins: fetchart embedart convert scrub replaygain lastgenre chroma web duplicates edit plexupdate lastimport discogs acousticbrainz spotify
directory: /music
library: /config/musiclibrary.blb
pluginpath: 
    -  /usr/lib/python3.8/site-packages/beetsplug/
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: no

convert:
    auto: no
    ffmpeg: /usr/bin/ffmpeg
    opts: -ab 320k -ac 2 -ar 48000
    max_bitrate: 320
    threads: 1

paths:
    default: Sorted/%left{$album,1}/$album ($year)/$album ($year) - $title
    singleton: Sorted/Non-Album/$artist - $title
    comp: Sorted/Compilations/%left{$album,1}/$album ($year)/$album ($year) - $title
    albumtype_soundtrack: Sorted/%left{$album,1}/$album ($year)/$album ($year) - $title

import:
    write: yes
    copy: no
    move: no
    resume: yes
    incremental: yes
    quiet_fallback: skip
    timid: no
    log: /config/beet.log

embedart:
    auto: yes
    remove_art_file: yes

fetchart:
    auto: yes

replaygain:
    auto: no

importreplace:
    item_fields: title artist artist_sort artist_credit
    album_fields: album artist albumartist
    replace:
        '(Original Motion Picture Soundtrack)': ''
```
But I am still getting the `(Original Motion Picture Soundtrack)` in the album title. The plugin is installed at the path that I have included (see below):
```
ash-4.4# pwd
/usr/lib/python3.8/site-packages/beetsplug
ash-4.4# ls
absubmit.py        bench.py   convert.py     embyupdate.py   fromfilename.py  importadded.py    ipfs.py        lyrics.py        mpdstats.py     plexupdate.py  smartplaylist.py     thumbnails.py
acousticbrainz.py  bpd        deezer.py      export.py       ftintitle.py     importfeeds.py    keyfinder.py   mbcollection.py  mpdupdate.py    __pycache__    sonosupdate.py       types.py
aura.py            bpm.py     discogs.py     fetchart.py     fuzzy.py         importreplace.py  kodiupdate.py  mbsubmit.py      parentwork.py   random.py      spotify.py           unimported.py
badfiles.py        bpsync.py  duplicates.py  filefilter.py   gmusic.py        info.py           lastgenre      mbsync.py        permissions.py  replaygain.py  subsonicplaylist.py  web
bareasc.py         bucket.py  edit.py        fish.py         hook.py          __init__.py       lastimport.py  metasync         playlist.py     rewrite.py     subsonicupdate.py    zero.py
beatport.py        chroma.py  embedart.py    freedesktop.py  ihate.py         inline.py         loadext.py     missing.py       play.py         scrub.py       the.py
```

I should probably add that I am using beets using docker. Let me know if you need any other information.

**Comment by edgars-supe** [comment]
Hi! Thanks for the report!
Perhaps I need to rub my tired eyes a bit harder, but I don't see that you've included `importreplace` in your `plugins` list. Looking at the readme, though, I see that the requirement isn't obvious, so I should make it clearer.

Also, regarding the config for the plugin itself, note that the "what to replace" value is regex, so you should escape the parentheses (`\(Original Motion Picture Soundtrack\)`, otherwise it will be parsed as a capturing group, and only the text inside will be replaced, leaving you with, e.g., `La La Land ()`.

**Comment by arsaboo** [comment]
When I include `importreplace` in `plugins`, I get the following error (and may be that is the cause):
```
ash-4.4# docker exec -it beets /bin/bash -c 'beet import "/music/Hindi Music/L"'
** error loading plugin importreplace:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/beets/plugins.py", line 276, in load_plugins
    namespace = __import__(modname, None, None)
ModuleNotFoundError: No module named 'beetsplug.importreplace'
```

**Comment by arsaboo** [comment]
Also, just an FYI, I ran the `pip install git+git://github.com/edgars-supe/beets-importreplace.git` command outside the docker. Not sure if that makes any difference.

**Comment by edgars-supe** [comment]
Ah, yeah, that will make a difference, because the Docker container won't have access to it if it's just installed on the host machine.

I don't use beets on Docker, so I'm not sure what the idiomatic way to install the plugin would be, but I have two ideas:
1) add a volume for your container that points to where `beets-importreplace` is installed (or install it to a specific directory),  and then include the directory in your `pluginpath`, eg., if you use docker-compose:
```
# in docker-compose.yml
    volumes:
        - /path/to/beets-importreplace:/plugins/beets-importreplace
 
# in beets config
pluginpath:
    - /plugins/beets-importreplace/beetsplug
```
2) Run the `pip install` command in docker:
```
docker-compose run beets pip install git+git://github.com/edgars-supe/beets-importreplace.git
```

I'm not sure either of them will work, I'm not too Docker-savvy.

**Comment by arsaboo** [comment]
Ok....so installed beets regularly (without Docker and it is working)...thanks a ton!

Can I ask you if something like the following is possible (and may be this is out of the current scope)?

I want to replace `'\(Original Motion Picture Soundtrack\)'` in the `album` field and the remaining two (`'& '` and `', '`) in the `albumartist` field.

```
importreplace:
    item_fields: ''
    album_fields: album artist albumartist
    replace:
        '\(Original Motion Picture Soundtrack\)': ''
        ', ': '\\\\'
        '& ': '\\\\'
```

So, is it possible to selectively apply the replacement to specific fields?

**Comment by arsaboo** [comment]
Also, I noted that sometimes the replacement does not work. Here's my config
```
importreplace:
    item_fields: ''
    album_fields: album albumartist genre
    replace:
        '\(Original Motion Picture Soundtrack\)': ''
        'Folk, World, & Country, Pop': 'Bollywood OST'
        ' & ': '\\\\'
        ' , ': '\\\\'
        ', ': '\\\\'
```

and it is still not replacing `Tanishk Bagchi & Dr. Zeus - Machine` to `Tanishk Bagchi\\Dr. Zeus - Machine`
```
/mnt/music/Hindi Music/M/Machine (2017) (6 items)
Correcting tags from:
    Various Artists - Machine
To:
    Tanishk Bagchi & Dr. Zeus - Machine
URL:
    https://musicbrainz.org/release/2078cf0f-f381-4d38-aa2d-1b2ec0df649e
(Similarity: 84.3%) (artist, tracks) (Digital Media, 2017, IN, T-Series)
 * Itna Tumhe... (#4)     -> Itna Tumhe (#1) (index)
 * Chatur Naar...         -> Chatur Naar
 * Barke An Fail... (#1)  -> Brake An Fail (#3) (index, title)
 * To Hi Toh Mera... (#6) -> To Hi Toh Mera (#4) (index)
 * Tera Junoon...         -> Tera Junoon
 * Cheez Badi... (#3)     -> Cheez Badi (#6) (index)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates?
```

**Comment by edgars-supe** [comment]
Unfortunately, that is currently not possible. Such an ability would be great, for sure. If you know some Python, feel free to give it a shot! I'll see if I can get it done in the next couple of weeks, perhaps.

**Comment by arsaboo** [comment]
I wish I knew Python that well :)

But I am thinking it should not be very difficult. I will be happy to test things out and discuss the feature addition.

**Comment by edgars-supe** [comment]
This plugin and some minor contributions I've made to `beets` itself are my first foray into Python. :)

It's probably not too difficult, no. The configuration I have in mind is something like:
```yaml
importreplace:
    replacements:
        - item_fields: foo bar
          album_fields: foo bar
          replace:
              'foo': 'bar'
              '[0-9]': '#'
        - album_fields: baz
          replace:
              '[A-Z]': ''
```
This would still allow you to specify multiple replacements for some fields, like how it works currently.

**Comment by arsaboo** [comment]
Not sure if you intended to have `album_fields` twice there in the configuration. Also, I am assuming that you added `replacements` there to add other features in the future?

**Comment by edgars-supe** [comment]
No, no, that's intentional. `replacements` would be a list of replacements you want to make, so you can specify that you want to do one replacement for some set of fields (`album`, for example), and different replacements for a different set of fields (`albumartist`).

So, the configuration you wanted a few comments before would look like this:
```yaml
importreplace:
    replacements:
        - album_fields: album
          replace:
              '\(Original Motion Picture Soundtrack\)': ''
        - album_fields: albumartist
          replace:
              ', ': '\\\\'
              '& ': '\\\\'
```
Maybe even `replacements` won't be necessary, but I'll see about that when I get there.

Perhaps the [YAML example on Wiki](https://en.wikipedia.org/wiki/YAML#Advanced_components) might make it clearer.
