### ISSUE TITLE
Replacing with everything before comma

### ISSUE THREAD

**Issue by arsaboo** [edgars-supe/beets-importreplace#5]
I am trying to replace multiple Album artists with the first album artist. I used the following:
```
importreplace:
  replacements:
    - album_fields: artist
      replace:
        '(^[^,]+),([^,]+).*': '$1'
```

However, this does not work. I was hoping that the first group (before the comma) will be used as a final string. Instead, it just places $1 in the artist field.
