### ISSUE TITLE
Search/replace is not supported for 'plural' fields (e.g. artists, artists_sort, artists_credit)

### ISSUE THREAD

**Issue by xe2io** [edgars-supe/beets-importreplace#7]
First off, thank you for creating this plugin!  I'm very happy that I found beets-importreplace- my use case is to override the style chosen in the Musicbrainz database for written tags (CAPS -> Titlecase).  

As it turns out, the [list-like](https://github.com/beetbox/beets/blob/master/beets/autotag/hooks.py#L103) AlbumInfo and TrackInfo fields (basically those of type `Optional[List[str]]`) aren't supported for the respective album_fields or item_fields parameters.

Using 'Umbrella' from the '[featured artist](https://musicbrainz.org/doc/Style/Artist_Credits#Featured_artists)' as an example: Jay-Z ends up with different capitalization since the 'feat.' artist credit is 'Jay-Z' but the canonical name is 'JAY-Z'.  This can be seen in the [release API response](https://musicbrainz.org/ws/2/release/60f8f1f5-485b-4637-8574-23f2bb98531f?inc=artists+artist-credits+release-groups).

The goal of this config file is to convert both variations to the lowercase 'jay-z', but it will raise a (IIRC) TypeError expecting a string instead of a list):
```
plugins: importreplace

importreplace:
  replacements:
    - item_fields: artist artist_sort artist_credit lyricist composer composer_sort arranger artists artists_sort artists_credit composer composer_sort arranger
      album_fields: artist artist_sort artist_credit artists artists_sort artists_credit
      replace:
        # Using 'Umbrella' [release/60f8f1f5-485b-4637-8574-23f2bb98531f] called out as a 'featured artist' Artist Credit example (https://musicbrainz.org/doc/Style/Artist_Credits#Featured_artists)
        # There are capitalization variations of Jay-Z (name-credit, sort name) and JAY-Z (artist name)
        # Contrieved demo example: change all to jay-z
        # Fun fact: musicbrainz returns a hyphen (U+2010)
        '(Jay|JAY)(.)Z': 'jay\2z'
```

I grabbed the audio from the listed streaming link listed for the release to test, but it might be possible to import any (valid) file as yt-dlp didn't have any metadata and we point to the release:
```
 beet -d . -l lib.db  -c config.yaml -vv import -c --search-id=60f8f1f5-485b-4637-8574-23f2bb98531f /tmp/Rihanna\ -\ Umbrella\ \(Orange\ Version\)\ \(Official\ Music\ Video\)\ ft.\ JAY-Z\ \[CvBfHwUxHIk\].m4a
```
I don't have exact error message but will have a PR to add support for the list-like fields soon :)
